### ISSUE TITLE
Music Cognition link

### ISSUE THREAD

**Issue by mtpearce** [c4dm/c4dmpoole#13]
Thank you, the website is looking great! I noticed two things: 
1. could the Music Cognition link on the front page go directly to the lab web page (like some of the other research themes): http://music-cognition.eecs.qmul.ac.uk/
2. the publications pages prior to 2008 retain the old page format.

Marcus

**Comment by danstowell** [comment]
Thanks Marcus, sorry slow response. OK I've made the direct link. We might want to think about this as a whole, whether we want consistency etc.

The older publications pages may get updated as part of the seismic rate of updates (it's a low priority)

**Comment by mtpearce** [comment]
Thanks Dan.
